# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.TextField(max_length=255),
        ),
    ]
